apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argo-ex
  description: argo-ex
  annotations:
    backstage.io/kubernetes-id: argo-ex
spec:
  type: website
  lifecycle: production
  owner: user:guest
